# Generated by Django 5.2.5 on 2025-08-27 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('resource_type', models.CharField(blank=True, choices=[('video', 'Video'), ('youtube', 'YouTube'), ('audio', 'Audio'), ('document', 'Document'), ('link', 'Link')], help_text='Type of resource', max_length=50)),
                ('url', models.URLField(blank=True, help_text='For YouTube or external links')),
                ('file', models.FileField(blank=True, help_text='For uploaded files', null=True, upload_to='course_resources/')),
                ('learning_style', models.CharField(choices=[('visual', 'Visual'), ('auditory', 'Auditory'), ('readwrite', 'Read/Write')], default='visual', max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='main.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
