# Generated by Django 5.2.5 on 2025-08-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_courseresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresource',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover/thumbnail image shown in the UI', null=True, upload_to='course_resource_thumbs/'),
        ),
    ]
