# Generated by Django 5.2.5 on 2025-08-31 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_classsession_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseresource',
            options={'ordering': ['position', 'created_at', 'id']},
        ),
    ]
