# Generated by Django 5.2.5 on 2025-08-31 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_courseresource_options'),
        ('main', '0011_message'),
    ]

    operations = [
    ]
