# Generated by Django 5.2.5 on 2025-08-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_merge_0011_alter_courseresource_options_0011_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
