# Generated by Django 5.2.5 on 2025-09-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_created_by'),
        ('main', '0013_game_points'),
    ]

    operations = [
    ]
