# Generated by Django 5.2.5 on 2025-10-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_merge_0004_add_course_classification_0015_resource_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
    ]
