# Generated by Django 5.2.5 on 2025-11-05 22:08

import main.models.survey
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_custom_user_survey'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customusersurvey',
            new_name='main_custom_is_acti_328df7_idx',
            old_name='main_custom_is_acti_01a86f_idx',
        ),
        migrations.RenameIndex(
            model_name='customusersurveyparticipant',
            new_name='main_custom_survey__6d6bbb_idx',
            old_name='main_custom_survey__d47e6a_idx',
        ),
        migrations.RenameIndex(
            model_name='customusersurveyquestion',
            new_name='main_custom_survey__ba16a8_idx',
            old_name='main_custom_survey__798f1d_idx',
        ),
        migrations.AlterField(
            model_name='customusersurvey',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, validators=[main.models.survey._validate_json_list]),
        ),
    ]
