# Generated by Django 5.2.5 on 2025-11-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_tutorapplication_tutorapplicationdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorapplicationdocument',
            name='doc_type',
            field=models.CharField(choices=[('id', 'Identity Document'), ('qualification', 'Qualification'), ('supporting', 'Supporting'), ('sace', 'SACE Certificate')], default='supporting', max_length=20),
        ),
    ]
